version: '3'

services:
	nodejs:
		build:
			context:
			dockerfile: Dockerfile
		image: nodejs
		container_name: nodejs
		restart: unless-stopped
		ports:
			- "80:8080"
		volumes:
			- . :/usr/src/app
			- node_modules:/usr/src/upp/node_modules
		command: /usr/src/app/node_modules/.bin/nodemon app.js
